[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
env = [
    "NAME = TestVPS0",
    "IP = 127.0.0.1",
    "ZONE = Kyiv",
    "FILES_URL = http://127.0.0.1:8081",
    "ORIGIN_URL = http://127.0.0.1:8081",
    "TEST_SERVER_PORT = 8081",
    "TEST = TRUE",
    "CHUNK_SIZE = 10",
    "CLEANER_SLEEP_TIME = 1",
    "FILE_EXPIRED_TIME = 0"
]
