name: Docker Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed
env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
          
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
    
    - name: Build and push Docker image
      env:
        DOCKER_REPO: sergienkoandrew/simple-cdn-server
      run: |
        docker build -t $DOCKER_REPO:${{ github.sha }} .
        docker tag $DOCKER_REPO:${{ github.sha }} $DOCKER_REPO:latest
        docker push $DOCKER_REPO:latest
