name: Python application

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CITY: Kyiv
      IP: 127.0.0.1
      NAME: TEST_VPS

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: test_database
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set env variables
      run: |
        echo "CITY=$CITY" >> $GITHUB_ENV
        echo "IP=$IP" >> $GITHUB_ENV
        echo "NAME=$NAME" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest tests
